POST http://localhost:8080/api/recipes
Content-Type: application/json

{
  "name": "Vegan Salad",
  "description": "A fresh and healthy vegan salad.",
  "imageUrl": "https://example.com/salad.jpg",
  "categories": ["Healty","Vegan"],
  "ingredients": [
    {
      "ingredientName": "Cucumber",
      "quantity": { "value": 200, "unit": "g" }
    }
  ],
  "steps": [
    {
      "stepIndex": 1,
      "instruction": "Chop all vegetables.",
      "duration": {"value": 10, "unit": "m"}
    },
    {
      "stepIndex": 2,
      "instruction": "Mix them with dressing.",
      "duration" : {"value": 3, "unit": "m"}
    }
  ]
}


